NAME = ft_tail
FILES = tail.c ft_atoi.c ft_str_is_numeric.c ft_putstr.c ft_strcmp.c
FLAGS = -Wall -Wextra -Werror

$(NAME):
	cc $(FLAGS) -o $(NAME) $(FILES)
all: $(NAME)

clean: 
	rm -f *.out
fclean: clean
	rm -f $(NAME)
